name: flutter_shimmer_skeleton
description: A Flutter package that provides shimmer loading skeleton widgets based on the official Flutter documentation.
version: 0.0.3
homepage: https://github.com/AlexGalitsky/flutter_shimmer_skeleton
repository: https://github.com/AlexGalitsky/flutter_shimmer_skeleton
issue_tracker: https://github.com/AlexGalitsky/flutter_shimmer_skeleton/issues
screenshots:
  - description: 'Flutter Shimmer skeleton logo.'
    path: images/logo.png
topics:
  - shimmer
  - skeleton
  - loading
  - ui
  - animation

environment:
  sdk: ^3.10.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
